language: java
jdk:
- oraclejdk8
sudo: false
install: true
addons:
  sonarqube:
    organization: savoir-technologies
    token:
      secure: qK19H8vlhFgX4trOhARqfTApOQYzfz3ltYALGdNmaePeVcEBGqcV+6c/RxLyqO35BJjnP/9Tyi7eYY87Qn4nWMW3EG3xNw4tc1c+UiEoZiA+H4bNjVitlsMGgV+r4eLx5pMzCQEy5a9QJr4Fmjb58AXJybWeIdM2dC3pIEEOJXIWaxetl74nA267lX34u2ux3cOp+m2A7aY/qOzjnKOkGvUnSgjValeo7WcXIrFz0LWIIMYrEY3pb67m+CP14d2WNldHeBmgeB5pQz9L3RvVj5HJKAC3QC32OEEf81QF9Rummur93L0XaR8ZSY0WgNJyJOLuvmXpG4Bx9tkpeU8T+ZLfbVI30VsyxwpgKibJnZ4xL7hDBEdMJ+2CuYTMzfAmZFHzlJbCG+V9CFZ9OPfs1MzOAK03Hq7tissJBFuGPL2azYaiivRnHCcGbf/VvQKGfrYmB2fOSD7dmGMQh2wL3hdih1Pd20h2g9y0HFADRlTK+ds/AZ+w90KcKsJDkW2ZvM5CmLE+IK78we5rvuoUAtk7AD95nQoKVQY3K9VqMM6ixw/l6a9LBMx1bkm5sRKjnblxwvd2YL6lgi1LdoJMuotaM02ip5CPgHHF5NBg7pYZN2RzpoCYjxl8vSxCntLE5HRTXaA5fpJPj3fFEE5tkB0jV+1uM1Bmk4AF4ly6kF0=
  apt:
    packages:
    - oracle-java8-installer
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  slack:
    secure: qt0Gp2eF4TA8Aok+lI88jO9f5bxluVa1ei09T4RYUA0FvDMXVusi/G72kp1SnwjafZMHUsXqI1uifZLlZuU6fYjs6lOl42kMOTP96FzO+CjkP5fF58zE21T/398CarYehSra090+/LNkkfHOT7OPt9JEiqpJIDwqGToEf32lolsKCPCfeBwysio4bOqq6LBZUwWHn1taYW+SvQNZrUBpauDo2k1b843ZsEa/BhtXJ4l164MAWiKKje7vRmxISRh3YvbAikUOPIQhEAWMCYzOifffHEU3Ji41+8QEmwGYbs/xQA0Dz+AjqgddUYIqjPmqlVvnt/BBNm8rzA0cbKftYbYfFtK+kvltkyZu76PKu5k9l7Kto5wMbmTgdFpkZahoUdYkEctN0VkqfsT6/+FlkpYr/TuLa3whzNR+xNGtP9AxtQMhLHK7LzOfyqzPNaUBVmzILR03VRtP5Tf6xECJUN2eARL9dh4hSAGFpD+lXCV86weF2ymSvjs8l+VM+X1Zi7WFJpwZQ0/A5VtkOobEybZH08ulqK+WljUjnASy0f6ASvoSS5kY8g8K4PaJz50dHP354ItUH/xNmPI9KiepD6mdRtL9RjOiQXM/DSJrkfqDKB353FdjQr8/0Fl3V9PPc1tMU3b6SqMcLZOPZT2d+CFjltjp9iiS7OgobImE8uE=
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: change     # options: [always|never|change] default: always
